### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by megaprogrammer777**
It`s my first homework and it`s so easy for me

### CODE REVIEW

**Comment by Rennercon** [comment]
Remove 1 and paste 2 near Hello World!

**Comment by megaprogrammer777** [comment]
But,why?

**Comment by megaprogrammer777** [comment]
Okey, i`m done

**Comment by megaprogrammer777** [comment]
can i do pull request?

**Comment by Rennercon** [comment]
Name the commits right in the next time

**Comment by Rennercon** [comment]
Aprooved

**Pull request merged**
